version: '3.8'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.51.0
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app


  nginx-app:
    container_name: nginx-app
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    ports:
      - 80:80
    networks:
      - app
    logging: *default-logging

  grafana:
    image: grafana/grafana:9.3.6
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./config/grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./config/grafana-jvm-dashboard.json:/var/lib/grafana/dashboards/jvm-dashboard.json
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      - app
    logging: *default-logging

  micronaut-app:
    image: micronaut/loki-logging:1.0.0
    container_name: micronaut
    build:
      context: .
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - app
    logging: *default-logging

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app
    logging: *default-logging

  promtail:
    image:  grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - ./config/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    depends_on:
      - loki
    networks:
      - app
    logging: *default-logging

networks:
  app:
    name: app