endpoints:
  prometheus:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

micronaut:
  application:
    name: demo
  server:
    port: 8080
  metrics:
    enabled:                      true
    binders.jvm.enabled:          true
    binders.uptime.enabled:       true
    binders.processor.enabled:    true
    binders.files.enabled:        true
    binders.logback.enabled:      true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

management:
  endpoints:
    web:
      exposure:
        include: 'health,info,prometheus'

