{
 "title": "Promtail Monitoring - Metrics and Logs",
 "description": "Monitor Promtail metrics and logs",
 "tags": [ "promtail" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource Loki", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(promtail_build_info,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   },
   { "name": "datasourceProm", "label": "Datasource Prometheus", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   { "name": "filter", "label": "LogQL Filter" }
  ]
 },
 "panels": [
  { "title": "Promtail - Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Promtail Version",
   "type": "stat",
   "description": "Deployed Promtail Version",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "promtail_build_info{job=~\"$job\", instance=~\"$instance.*\"} ",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Current Sent Bytes",
   "type": "stat",
   "description": "Current number of bytes sent. ( Real Time )",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(promtail_sent_bytes_total[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active TCP connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "tcp_connections{protocol=\"http\"}",
     "legendFormat": "{{job}} // {{protocol}} {{instance}} "
    }
   ]
  },
  {
   "title": "Request Latency - 99th Percentile Latency",
   "type": "timeseries",
   "description": "99th percentile latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(promtail_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance.*\"}[$__interval])) by (le))",
     "legendFormat": "Request Latency P95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(promtail_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance.*\"}[$__interval])) by (le))",
     "legendFormat": "Request Latency P75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(promtail_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance.*\"}[$__interval])) by (le))",
     "legendFormat": "Request Latency P55"
    }
   ]
  },
  {
   "title": "Encoded and Send Bytes - Overtime",
   "type": "timeseries",
   "description": "- Encoded: Number of bytes encoded and ready to send.\n- Send: Number of bytes sent. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(promtail_encoded_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "Encoded Bytes"
    },
    {
     "expr": "rate(promtail_sent_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "Send Bytes"
    }
   ]
  },
  {
   "title": "Encoded and Send - Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(promtail_sent_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])"
    },
    {
     "expr": "increase(promtail_sent_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[24h])"
    },
    {
     "expr": "rate(promtail_encoded_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])"
    },
    {
     "expr": "increase(promtail_encoded_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[24h])"
    }
   ]
  },
  {
   "title": "Error Requests and Logs Count - Overtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(promtail_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance.*\",status_code=~\"5.*\"}[$interval])) by (job, instance) / sum(rate(promtail_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance.*\"}[$interval])) by (job, instance)",
     "legendFormat": "Error Requests"
    }
   ]
  },
  {
   "title": "Dropped Bytes - Overtime",
   "type": "timeseries",
   "description": "- Dropped Bytes: Number of bytes dropped because failed to be sent to the ingester after all retries.\n- Dropped Entries: Number of log entries dropped because failed to be sent to the ingester after all retries.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(promtail_dropped_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "Dropped Bytes - {{reason}}"
    },
    {
     "expr": "rate(promtail_dropped_entries_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "Dropped Entries - {{reason}}"
    }
   ]
  }
 ]
}