# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # scrape micronaut prometheus
  - job_name: "prometheus"
    metrics_path: '/prometheus'
    scrape_interval: 500ms
    static_configs:
      - targets: ["micronaut-app:8080"]

  # scrape loki prometheus
  - job_name: "loki metrics"
    metrics_path: '/metrics'
    scrape_interval: 500ms
    static_configs:
      - targets: ["loki:3100"]

  # scrape promtail prometheus
  - job_name: "promtail metrics"
    metrics_path: '/metrics'
    scrape_interval: 500ms
    static_configs:
      - targets: [ "promtail:9080" ]